---
id: php-study-115
base_name: fast-japanese-full-text-search-with-php-and-postgresql-and-pgroonga
tags:
- rabbit
- php
- postgresql
- full-text-search
- japanese
- pgroonga
- phpstudy
presentation_date: 2017-06-28
version: 2017.6.28.3
licenses:
- CC BY 3.0
- CC BY-SA 4.0
slideshare_id: phpstudy115
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user:
